#!/usr/bin/env bash
# configure a brand new NGINX server

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tes /var/www/html/index.html

sudo ed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
