#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and Hi

counter=1
while [ $counter -ne 101 ]
do
	if [ $(expr $counter % 3) == 0 ] && [ $(expr $counter % 5) == 0 ] 
	then
        echo "FizzBuzz"
    elif [ $(expr $counter % 5) == 0 ]
    then
        echo "Buzz"
    elif [ $(expr $counter % 3) == 0 ]
    then
        echo "Fizz"
    else
        echo $counter
    fi
	((counter++))
done