#!/usr/bin/env bash
#fake clock

hour=0
min=1
echo "Hour: ${hour}"
while [ $hour -le 12 ]
do
	if [ $min -lt 60 ]
	then
		echo $min
	elif [ $min -gt 59 ]
	then
		hour=$((hour + 1))
		if [ $hour -ne 13 ]
		then
			echo "Hour: ${hour}"
		fi
		min=$((0))
	fi
	min=$((min + 1))
done
